name: EconomyPro
version: @version@
main: net.propromp.economypro.Main
api-version: 1.15
softdepend: [Vault]
commands:
  money:
    description: check your balance
  bank:
    description: manage your bank
    usage: /bank help
  balance:
    description: manage balance
    usage: /balance help
  pay:
    description: pay <player> <amount>
    usage: /pay <player> <amount>
  economypro:
    description: shows help & settings
  balancetop:
    description: Displays Top 10
permissions:
  economypro.*:
    children:
      - economypro.money
      - economypro.bank
      - economypro.balance.set
      - economypro.balance.get
      - economypro.pay
      - economypro.economypro
      - economypro.balancetop
    default: op
  economypro.money:
    default: true
  economypro.bank:
    default: true
  economypro.balance.set:
    default: op
  economypro.balance.get:
    default: true
  economypro.pay:
    default: true
  economypro.economypro.help:
    default: true
  economypro.economypro.settings:
    default: op
  economypro.balncetop:
    default: true